plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("com.google.devtools.ksp")
    id("com.google.gms.google-services")
}

android {
    namespace = "com.antidetect.browser"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.antidetect.browser"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    // Debug keystore is auto-generated by AGP; reuse it for a testable "release" APK
    signingConfigs {
        getByName("debug")
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            // Sign with debug key so the APK is installable without a Play keystore
            signingConfig = signingConfigs.getByName("debug")
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
        debug {
            isMinifyEnabled = false
            signingConfig = signingConfigs.getByName("debug")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
        viewBinding = false
        dataBinding = false
    }

    composeOptions {
        // Must match Kotlin 1.9.24
        kotlinCompilerExtensionVersion = "1.5.14"
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
            excludes += "META-INF/DEPENDENCIES"
            excludes += "META-INF/LICENSE"
            excludes += "META-INF/LICENSE.txt"
            excludes += "META-INF/NOTICE"
            excludes += "META-INF/NOTICE.txt"
        }
        jniLibs {
            // Required so GeckoView .so are extracted correctly on many devices
            useLegacyPackaging = true
        }
    }

    lint {
        checkReleaseBuilds = false
    }
}

dependencies {
    // ---- AndroidX (pinned) ----
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("com.google.android.material:material:1.12.0")
    implementation("androidx.activity:activity-compose:1.9.1")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.4")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.4")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.8.4")

    // ---- Compose BOM 2024.06 (compileSdk 35 + AGP 8.6) ----
    val composeBom = platform("androidx.compose:compose-bom:2024.06.00")
    implementation(composeBom)
    androidTestImplementation(composeBom)
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.navigation:navigation-compose:2.7.7")
    debugImplementation("androidx.compose.ui:ui-tooling")

    // ---- GeckoView release 128 (HTTP 200 on maven.mozilla.org, no compileSdk 37) ----
    implementation("org.mozilla.geckoview:geckoview:128.0.20240725162350")

    // ---- Room ----
    implementation("androidx.room:room-runtime:2.6.1")
    implementation("androidx.room:room-ktx:2.6.1")
    ksp("androidx.room:room-compiler:2.6.1")

    // ---- Coroutines / Gson ----
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.8.1")
    implementation("com.google.code.gson:gson:2.11.0")

    // ---- Firebase (Firestore device auth – just mark devices in console) ----
    implementation(platform("com.google.firebase:firebase-bom:33.1.2"))
    implementation("com.google.firebase:firebase-firestore-ktx")
}


// Block transitive upgrades that trigger AAR metadata errors
configurations.all {
    resolutionStrategy {
        force("androidx.core:core:1.13.1")
        force("androidx.core:core-ktx:1.13.1")
        force("androidx.lifecycle:lifecycle-runtime:2.8.4")
        force("androidx.lifecycle:lifecycle-runtime-ktx:2.8.4")
        force("androidx.lifecycle:lifecycle-runtime-compose:2.8.4")
        force("androidx.lifecycle:lifecycle-viewmodel:2.8.4")
        force("androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.4")
        force("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.4")
        force("androidx.activity:activity:1.9.1")
        force("androidx.activity:activity-compose:1.9.1")
        force("androidx.activity:activity-ktx:1.9.1")
        force("androidx.annotation:annotation:1.8.0")
        force("androidx.transition:transition:1.5.0")
    }
}
